"""One thin layer over SQLite and PostgreSQL.

Not an ORM, and deliberately not a general one: the application writes plain SQL
in a subset both databases accept, and this module smooths over the handful of
places where they genuinely differ.

  * **placeholders** — SQL is written with `?` throughout and rewritten to `%s`
    for PostgreSQL. That is safe only because no statement here puts a `?` inside
    a string literal; `sql()` refuses any statement that mixes the two, so the
    assumption cannot rot silently.
  * **identity columns** — `INTEGER PRIMARY KEY AUTOINCREMENT` against
    `GENERATED BY DEFAULT AS IDENTITY`.
  * **floats** — `REAL` is a 32-bit type in PostgreSQL, which is not enough for
    an epoch timestamp; it maps to `DOUBLE PRECISION` there.
  * **introspection** — `PRAGMA table_info` against `information_schema`.

Rows come back as plain dicts from both, so callers never see a driver type.

Both support `RETURNING` (SQLite since 3.35), so inserts read their new row back
the same way rather than reaching for `lastrowid`, which psycopg has no
equivalent of.
"""

from __future__ import annotations

import re
import sqlite3
import threading
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Iterator
from urllib.parse import urlparse

SQLITE, POSTGRES = "sqlite", "postgresql"


class DatabaseError(Exception):
    pass


def _sqlite_rows(cursor: sqlite3.Cursor, row: tuple) -> dict[str, Any]:
    return {column[0]: row[index] for index, column in enumerate(cursor.description)}


class Database:
    """A connection factory that knows which dialect it is talking to."""

    def __init__(self, url: str) -> None:
        self.url = url.strip()
        self.kind = SQLITE if self._is_sqlite(self.url) else POSTGRES
        self._pool: Any = None
        self._lock = threading.Lock()

        if self.kind == SQLITE:
            self.path = self._sqlite_path(self.url)
            self.path.parent.mkdir(parents=True, exist_ok=True)
        else:
            self.path = None

    # -- description ------------------------------------------------------- #

    @staticmethod
    def _is_sqlite(url: str) -> bool:
        return url.startswith("sqlite:") or not re.match(r"^[a-zA-Z][\w+]*://", url)

    @staticmethod
    def _sqlite_path(url: str) -> Path:
        if url.startswith("sqlite:"):
            # sqlite:///relative/path or sqlite:////absolute/path
            rest = url[len("sqlite:") :].lstrip("/")
            absolute = url.startswith("sqlite:////")
            return Path("/" + rest) if absolute else Path(rest)
        return Path(url)

    @property
    def describe(self) -> str:
        if self.kind == SQLITE:
            return f"SQLite at {self.path}"
        parts = urlparse(self.url)
        where = parts.hostname or "localhost"
        name = (parts.path or "/").lstrip("/") or "(default)"
        return f"PostgreSQL {name} on {where}:{parts.port or 5432}"

    # -- dialect ----------------------------------------------------------- #

    @property
    def identity(self) -> str:
        return (
            "INTEGER PRIMARY KEY AUTOINCREMENT"
            if self.kind == SQLITE
            else "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        )

    @property
    def float_type(self) -> str:
        # PostgreSQL's REAL is single precision: an epoch second would lose the
        # sub-second part and then some.
        return "REAL" if self.kind == SQLITE else "DOUBLE PRECISION"

    def sql(self, statement: str) -> str:
        """Rewrite `?` placeholders for the driver in use.

        Statements with no `?` pass through untouched, which is what lets DDL
        carry `DEFAULT ''`. Only a statement that mixes placeholders with quoted
        literals is refused, because there the naive rewrite could corrupt the
        literal — and nothing in this codebase needs to do that.
        """
        if self.kind == SQLITE or "?" not in statement:
            return statement
        if "'" in statement:
            raise DatabaseError(
                "SQL mixing `?` placeholders with a quoted literal cannot be "
                "rewritten safely — pass the value as a parameter instead:\n" + statement
            )
        return statement.replace("?", "%s")

    # -- connections ------------------------------------------------------- #

    # Fail fast on a wrong host or a firewall, rather than sitting on libpq's
    # default timeout. Overridden by connect_timeout in the URL.
    CONNECT_TIMEOUT = 8

    def _conninfo(self) -> str:
        if "connect_timeout=" in self.url:
            return self.url
        separator = "&" if "?" in self.url else "?"
        return f"{self.url}{separator}connect_timeout={self.CONNECT_TIMEOUT}"

    def _ensure_pool(self) -> Any:
        if self._pool is None:
            with self._lock:
                if self._pool is None:
                    from psycopg_pool import ConnectionPool
                    from psycopg.rows import dict_row

                    self._pool = ConnectionPool(
                        self._conninfo(),
                        min_size=1,
                        max_size=8,
                        kwargs={"row_factory": dict_row},
                        open=True,
                        timeout=self.CONNECT_TIMEOUT + 2,
                    )
        return self._pool

    def verify(self) -> None:
        """Prove the database is reachable and writable, with a usable error.

        Without this, a wrong host or password surfaces thirty seconds later as
        "couldn't get a connection", which names neither the database nor the
        likely cause — precisely when someone is pointing the app at a new server
        and needs to know which of the two went wrong.
        """
        try:
            if self.kind == POSTGRES:
                # A direct connection, not the pool: the pool reports only
                # "couldn't get a connection", while libpq says whether it was
                # the host, the database, the role or the password.
                import psycopg

                with psycopg.connect(self._conninfo()) as conn:
                    conn.execute("SELECT 1")
            else:
                with self.connect() as conn:
                    conn.scalar("SELECT 1 AS ok")
        except Exception as exc:  # noqa: BLE001 - re-raised with context below
            detail = str(exc).strip() or type(exc).__name__
            if self.kind == SQLITE:
                raise DatabaseError(f"Cannot open {self.describe}: {detail}") from exc
            raise DatabaseError(
                f"Cannot reach {self.describe}.\n"
                f"  {detail}\n"
                "  Check that the server accepts connections from this host "
                "(listen_addresses and pg_hba.conf), that the database and role exist, "
                "and that the password in DATABASE_URL is right."
            ) from exc

    @contextmanager
    def connect(self) -> Iterator[Any]:
        """A connection with its own transaction, committed on a clean exit."""
        if self.kind == SQLITE:
            conn = sqlite3.connect(self.path, timeout=10)
            conn.row_factory = _sqlite_rows
            conn.execute("PRAGMA journal_mode=WAL")
            conn.execute("PRAGMA foreign_keys=ON")
            try:
                with conn:  # commits, or rolls back on an exception
                    yield _Wrapped(self, conn)
            finally:
                conn.close()
        else:
            with self._ensure_pool().connection() as conn:
                yield _Wrapped(self, conn)

    def close(self) -> None:
        if self._pool is not None:
            self._pool.close()
            self._pool = None

    # -- introspection ------------------------------------------------------ #

    def columns(self, conn: "_Wrapped", table: str) -> set[str]:
        if self.kind == SQLITE:
            rows = conn.all(f"PRAGMA table_info({table})")
            return {row["name"] for row in rows}
        rows = conn.all(
            "SELECT column_name FROM information_schema.columns WHERE table_name = ?",
            (table,),
        )
        return {row["column_name"] for row in rows}

    def table_exists(self, conn: "_Wrapped", table: str) -> bool:
        return bool(self.columns(conn, table))


class _Wrapped:
    """A connection that rewrites placeholders and always hands back dicts."""

    def __init__(self, db: Database, conn: Any) -> None:
        self._db = db
        self._conn = conn

    def execute(self, statement: str, params: tuple | list = ()) -> Any:
        return self._conn.execute(self._db.sql(statement), tuple(params))

    def all(self, statement: str, params: tuple | list = ()) -> list[dict[str, Any]]:
        return list(self.execute(statement, params).fetchall())

    def one(self, statement: str, params: tuple | list = ()) -> dict[str, Any] | None:
        row = self.execute(statement, params).fetchone()
        return dict(row) if row is not None else None

    def many(self, statement: str, rows: list[tuple]) -> None:
        if not rows:
            return
        prepared = self._db.sql(statement)
        if self._db.kind == SQLITE:
            self._conn.executemany(prepared, rows)
        else:
            with self._conn.cursor() as cur:
                cur.executemany(prepared, rows)

    def scalar(self, statement: str, params: tuple | list = ()) -> Any:
        row = self.one(statement, params)
        return next(iter(row.values())) if row else None


def connect_url(settings_url: str) -> Database:
    return Database(settings_url)
